/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DriverAuthorizationAdminRole;

import Business.Authorization.DriverAuthorizationAdmin;
import Business.DB4OUtil.DB4OUtil;
import Business.Driver.PrivateDriver;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Hospital.Patient;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class DriverAuthorizationAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverAuthorizationAdminWorkAreaJPanel
     */
         private static EcoSystem system;
    private static DB4OUtil dB4OUtil;
    private static JPanel userProcessorcontainer;
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private DriverAuthorizationAdmin driverAdminLogin;

    public DriverAuthorizationAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business, DriverAuthorizationAdmin driverAdminLogin) {
        initComponents();
         this.system = business;
        this.dB4OUtil = dB4OUtil;
        this.userProcessorcontainer = userProcessContainer;
    this.userProcessContainer=userProcessContainer;
    this.account=account;
    this.organization=organization;
    this.enterprise=enterprise;
    this.business=business;
    this.driverAdminLogin=driverAdminLogin;
    this.setSize(1680, 1050);
    populatePrivateDriverDetails();
    }
   
public void populatePrivateDriverDetails(){
   
    
    
     DefaultTableModel model = (DefaultTableModel) privDriverjTable.getModel();
        model.setRowCount(0);

        for(PrivateDriver privDriver : system.getPrivateDriverDirectory().getPrivateDriverDirectory()){
            if( !privDriver.isIsAuthorized()){
                Object[] row=new Object[5];
                row[0]=privDriver.getId();
                row[1]=privDriver.getDriverLastName()+", "+privDriver.getDriverFirstName();
                row[2]=privDriver.getPhoneNumber();
                row[3]=privDriver.getAge();
                row[4]=privDriver.getPrivateVehicleNumber();
                model.addRow(row);
            }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        privDriverjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewDlButton = new javax.swing.JLabel();
        ConfirmButton1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        privDriverjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ptient Id", "Driver's Fullname", "Phone Number", "Age", "Private car number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(privDriverjTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 583, 151));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Click here to see DL of selected Driver :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, 20));

        viewDlButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewDlButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewDlButton.setText("View DL");
        viewDlButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewDlButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewDlButtonMousePressed(evt);
            }
        });
        add(viewDlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 114, 26));

        ConfirmButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ConfirmButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConfirmButton1.setText("Confirm");
        ConfirmButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ConfirmButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ConfirmButton1MousePressed(evt);
            }
        });
        add(ConfirmButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 113, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/driver (1).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 250, 260));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/driver (2).png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, 130));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("HELLO AUTHORIZATION ADMIN!");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 23));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Driver Requests");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDlButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDlButtonMousePressed
        // TODO add your handling code here:
        
        int selectedRowIndex = privDriverjTable.getSelectedRow();
        if (privDriverjTable.getSelectedRowCount() == 1) {
        
            try {
                DefaultTableModel model = (DefaultTableModel) privDriverjTable.getModel();
                Integer privdriverId = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
                PrivateDriver privateDriver=system.getPrivateDriverDirectory().getUserById(privdriverId);
                byte[] image= privateDriver.getLicImage();
                //additional code
                InputStream is = new ByteArrayInputStream(image);
                BufferedImage img = ImageIO.read(is);
                Image dimg = img.getScaledInstance(186, 151,
                        Image.SCALE_SMOOTH);
                //additional code
                JOptionPane.showMessageDialog(null,"", "Driving License Image", + JOptionPane.INFORMATION_MESSAGE,   new ImageIcon(dimg));
            } catch (IOException ex) {
                Logger.getLogger(DriverAuthorizationAdminWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select one row to see Driving licanse");
            return;
        }     
    }//GEN-LAST:event_viewDlButtonMousePressed

    private void ConfirmButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButton1MousePressed
        // TODO add your handling code here:
        
        int selectedRowIndex = privDriverjTable.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) privDriverjTable.getModel();
       
        Integer privateDriverId = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
        PrivateDriver privateDriver = system.getPrivateDriverDirectory().getUserById(privateDriverId);
        if (privDriverjTable.getSelectedRowCount() == 1) {
        
             
             privateDriver.setIsAuthorized(true);
             JOptionPane.showMessageDialog(null, "Driver has been Authorized successfully");
             populatePrivateDriverDetails();
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select one row to confirm");
            return;
        }
    }//GEN-LAST:event_ConfirmButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable privDriverjTable;
    private javax.swing.JLabel viewDlButton;
    // End of variables declaration//GEN-END:variables
}
