/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DriverAuthorizationAdminRole;

import Business.DB4OUtil.DB4OUtil;
import Business.Driver.PrivateDriver;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash
 */
public class DriverAuthorizationAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverAuthorizationAdminWorkAreaJPanel
     */
         private static EcoSystem system;
    private static DB4OUtil dB4OUtil;
    private static JPanel userProcessorcontainer;
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    public DriverAuthorizationAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
         this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.userProcessorcontainer = userProcessContainer;
    this.userProcessContainer=userProcessContainer;
    this.account=account;
    this.organization=organization;
    this.enterprise=enterprise;
    this.business=business;
    this.setSize(1680, 1050);
    populatePrivateDriverDetails();
    }
   
public void populatePrivateDriverDetails(){
   
    
    
     DefaultTableModel model = (DefaultTableModel) privDriverjTable.getModel();
        model.setRowCount(0);

        for(PrivateDriver privDriver : system.getPrivateDriverDirectory().getPrivateDriverDirectory()){
            if(!privDriver.isIsAuthorized()){
                Object[] row=new Object[4];
                row[0]=privDriver.getDriverLastName()+", "+privDriver.getDriverFirstName();
                row[1]=privDriver.getPhoneNumber();
                row[2]=privDriver.getAge();
                row[3]=privDriver.getPrivateVehicleNumber();
                model.addRow(row);
            }
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        privDriverjTable = new javax.swing.JTable();
        ConfirmButton = new javax.swing.JButton();

        jLabel8.setText("Your pending Request");

        privDriverjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Driver's Fullname", "Phone Number", "Age", "Private car number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(privDriverjTable);

        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(ConfirmButton)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = privDriverjTable.getSelectedRow();
        if (privDriverjTable.getSelectedRowCount() == 1) {
        
             PrivateDriver privateDriver=system.getPrivateDriverDirectory().getUserByFullName((String)privDriverjTable.getValueAt(selectedRowIndex, 0));
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable privDriverjTable;
    // End of variables declaration//GEN-END:variables
}
