/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import ui.AmbulanceDriverRole.AmbulanceDriverRegistrationJPanel;
import ui.CampAdminRole.CampAdminRegistrationJPanel;
import ui.DriverAuthorizationAdminRole.DriverAuthorizationRegistrationJPanel;
import ui.HospitalAdminRole.HospitalAdminRegistrationJPanel;
import ui.NGORole.NGORegistrationJPanel;
import ui.PatientAuthorizationAdminRole.PatientAuthorizationRegistrationJPanel;
import ui.PatientCareStaffRole.PatientCareStaffRegistrationJPanel;
import ui.PatientRole.PatientRegistrationJPanel;
import ui.PrivateDriverRole.PrivateDriverRegistrationJPanel;

/**
 *
 * @author aishwarya
 */
public class RegisterJPanel extends javax.swing.JPanel {

    private static EcoSystem system;
    private static DB4OUtil dB4OUtil;
    private static JPanel mainContainer;
    private static JPanel topPanel;

    public RegisterJPanel(JPanel mainContainer, JPanel topPanel, EcoSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        this.topPanel = topPanel;
        this.mainContainer = mainContainer;
        this.setSize(1680, 1050);
        topPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        patientBtn = new javax.swing.JLabel();
        hospitalBtn = new javax.swing.JLabel();
        patientCareStaffBtn = new javax.swing.JLabel();
        ngoBtn = new javax.swing.JLabel();
        campBtn = new javax.swing.JLabel();
        ambulanceBtn = new javax.swing.JLabel();
        privateDriverBtn = new javax.swing.JLabel();
        driverAuthBtn = new javax.swing.JLabel();
        patientAuthBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerDetails.setBackground(new java.awt.Color(255, 244, 244));
        registerDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("PLEASE REGISTER HERE");
        registerDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 330, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Hospital:");
        registerDetails.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Voluntary:");
        registerDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Transportation:");
        registerDetails.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Authorization:");
        registerDetails.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 150, -1));

        patientBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patientBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientBtn.setText("Patient");
        patientBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        patientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientBtnMousePressed(evt);
            }
        });
        registerDetails.add(patientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 140, 30));

        hospitalBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hospitalBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalBtn.setText("Hospital Admin");
        hospitalBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hospitalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hospitalBtnMousePressed(evt);
            }
        });
        registerDetails.add(hospitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 140, 30));

        patientCareStaffBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patientCareStaffBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientCareStaffBtn.setText("Patient Care Staff");
        patientCareStaffBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        patientCareStaffBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientCareStaffBtnMousePressed(evt);
            }
        });
        registerDetails.add(patientCareStaffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 140, 30));

        ngoBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ngoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ngoBtn.setText("NGO Admin");
        ngoBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ngoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ngoBtnMousePressed(evt);
            }
        });
        registerDetails.add(ngoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 160, 30));

        campBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campBtn.setText("Camp Site Admin");
        campBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campBtnMousePressed(evt);
            }
        });
        registerDetails.add(campBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 160, 30));

        ambulanceBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ambulanceBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ambulanceBtn.setText("Ambulance Driver");
        ambulanceBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ambulanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ambulanceBtnMousePressed(evt);
            }
        });
        registerDetails.add(ambulanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 160, 30));

        privateDriverBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        privateDriverBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        privateDriverBtn.setText("Private Driver");
        privateDriverBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        privateDriverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                privateDriverBtnMousePressed(evt);
            }
        });
        registerDetails.add(privateDriverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 160, 30));

        driverAuthBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        driverAuthBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverAuthBtn.setText("Driver Authorization Admin");
        driverAuthBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        driverAuthBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                driverAuthBtnMousePressed(evt);
            }
        });
        registerDetails.add(driverAuthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 230, 30));

        patientAuthBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patientAuthBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientAuthBtn.setText("Patient Authorization Admin");
        patientAuthBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        patientAuthBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientAuthBtnMousePressed(evt);
            }
        });
        registerDetails.add(patientAuthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 210, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        registerDetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        registerDetails.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 390, 270));

        add(registerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 1000, 687));
    }// </editor-fold>//GEN-END:initComponents

    private void patientBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientBtnMousePressed
        // TODO add your handling code here:
        PatientRegistrationJPanel panel = new PatientRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_patientBtnMousePressed

    private void hospitalBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospitalBtnMousePressed
        // TODO add your handling code here:

        HospitalAdminRegistrationJPanel panel = new HospitalAdminRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_hospitalBtnMousePressed

    private void patientCareStaffBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientCareStaffBtnMousePressed
        // TODO add your handling code here:
        PatientCareStaffRegistrationJPanel panel = new PatientCareStaffRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_patientCareStaffBtnMousePressed

    private void ngoBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ngoBtnMousePressed
        // TODO add your handling code here:

        NGORegistrationJPanel panel = new NGORegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_ngoBtnMousePressed

    private void driverAuthBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driverAuthBtnMousePressed
        // TODO add your handling code here:

        DriverAuthorizationRegistrationJPanel panel = new DriverAuthorizationRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_driverAuthBtnMousePressed

    private void patientAuthBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientAuthBtnMousePressed
        // TODO add your handling code here:

        PatientAuthorizationRegistrationJPanel panel = new PatientAuthorizationRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_patientAuthBtnMousePressed

    private void campBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campBtnMousePressed
        // TODO add your handling code here:
        CampAdminRegistrationJPanel j = new CampAdminRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", j);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_campBtnMousePressed

    private void ambulanceBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ambulanceBtnMousePressed
        // TODO add your handling code here:
        AmbulanceDriverRegistrationJPanel panel = new AmbulanceDriverRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);

    }//GEN-LAST:event_ambulanceBtnMousePressed

    private void privateDriverBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_privateDriverBtnMousePressed
        // TODO add your handling code here:
        PrivateDriverRegistrationJPanel panel = new PrivateDriverRegistrationJPanel(mainContainer, topPanel, system, dB4OUtil);
        mainContainer.add("workArea", panel);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        mainContainer.setVisible(true);
        topPanel.setVisible(false);
    }//GEN-LAST:event_privateDriverBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ambulanceBtn;
    private javax.swing.JLabel campBtn;
    private javax.swing.JLabel driverAuthBtn;
    private javax.swing.JLabel hospitalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel ngoBtn;
    private javax.swing.JLabel patientAuthBtn;
    private javax.swing.JLabel patientBtn;
    private javax.swing.JLabel patientCareStaffBtn;
    private javax.swing.JLabel privateDriverBtn;
    private javax.swing.JPanel registerDetails;
    // End of variables declaration//GEN-END:variables
}
