/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        populateTree(); 
    }
    
    public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
        ArrayList<Network> networkList=ecosystem.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i=0;i<networkList.size();i++){
            network=networkList.get(i);
            networkNode=new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList=network.getEnterpriseDirectory().getEnterpriseList();
            for(int j=0; j<enterpriseList.size();j++){
                enterprise=enterpriseList.get(j);
                enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organizationList=enterprise.getOrganizationDirectory().getOrganizationList();
                for(int k=0;k<organizationList.size();k++){
                    organization=organizationList.get(i);
                    organizationNode=new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        rightjPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        btnManageNetwork = new javax.swing.JLabel();
        btnManageEnterprise = new javax.swing.JLabel();
        btnManageAdmin = new javax.swing.JLabel();
        btnpie = new javax.swing.JLabel();
        btnbar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        rightjPanel.setBackground(new java.awt.Color(214, 41, 41));
        rightjPanel.setLayout(new java.awt.CardLayout());
        jSplitPane.setRightComponent(rightjPanel);

        jPanel1.setBackground(new java.awt.Color(255, 198, 142));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTree.setBackground(new java.awt.Color(255, 225, 196));
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 170));

        btnManageNetwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManageNetworkMousePressed(evt);
            }
        });
        jPanel1.add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 170, 29));

        btnManageEnterprise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManageEnterpriseMousePressed(evt);
            }
        });
        jPanel1.add(btnManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, 26));

        btnManageAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageAdmin.setText("Manage Enterprise Admin");
        btnManageAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnManageAdminMousePressed(evt);
            }
        });
        jPanel1.add(btnManageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 190, 27));

        btnpie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpie.setText("Pie Chart");
        btnpie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpieMousePressed(evt);
            }
        });
        jPanel1.add(btnpie, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 175, 170, 20));

        btnbar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbar.setText("Bar Graph");
        btnbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbarMousePressed(evt);
            }
        });
        jPanel1.add(btnbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 215, 170, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Selected Node:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 394, 130, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph-bar (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hospital (2).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie-chart.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 30, 30));

        jSplitPane.setLeftComponent(jPanel1);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        
        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
        if(selectedNode!=null){
           
        }
    }//GEN-LAST:event_jTreeValueChanged

    private void btnManageNetworkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageNetworkMousePressed
        // TODO add your handling code here:
        
         ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(rightjPanel, ecosystem);
        rightjPanel.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)rightjPanel.getLayout();
        layout.next(rightjPanel);
        
    }//GEN-LAST:event_btnManageNetworkMousePressed

    private void btnManageEnterpriseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageEnterpriseMousePressed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel=new ManageEnterpriseJPanel(rightjPanel, ecosystem);
        rightjPanel.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)rightjPanel.getLayout();
        layout.next(rightjPanel);
    }//GEN-LAST:event_btnManageEnterpriseMousePressed

    private void btnManageAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageAdminMousePressed
        // TODO add your handling code here:
       ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminJPanel(rightjPanel, ecosystem);
        rightjPanel.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)rightjPanel.getLayout();
        layout.next(rightjPanel); 
    }//GEN-LAST:event_btnManageAdminMousePressed

    private void btnpieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpieMousePressed
        // TODO add your handling code here:
        
        PieCHartUserNumberStatistics piechart = new PieCHartUserNumberStatistics(rightjPanel, ecosystem);
        rightjPanel.add("PieCHartUserNumberStatistics",piechart);
        CardLayout layout = (CardLayout) rightjPanel.getLayout();
        layout.next(rightjPanel);
    }//GEN-LAST:event_btnpieMousePressed

    private void btnbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbarMousePressed
        // TODO add your handling code here:
        
        PatientStatusBarChart piechart = new PatientStatusBarChart(rightjPanel, ecosystem);
        rightjPanel.add("PatientStatusBarChart",piechart);
        CardLayout layout = (CardLayout) rightjPanel.getLayout();
        layout.next(rightjPanel);
    }//GEN-LAST:event_btnbarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnManageAdmin;
    private javax.swing.JLabel btnManageEnterprise;
    private javax.swing.JLabel btnManageNetwork;
    private javax.swing.JLabel btnbar;
    private javax.swing.JLabel btnpie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    private javax.swing.JPanel rightjPanel;
    // End of variables declaration//GEN-END:variables
}
