/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;

import Business.Hospital.Patient;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author aishwarya
 */
public class PatientCheckMyStatusCamplJPanel extends javax.swing.JPanel {

    private Patient p;
    private JPanel userProcessContainer;

    /**
     * Creates new form PatientCheckMyStatusJPanel
     */
    public PatientCheckMyStatusCamplJPanel(Patient p, JPanel userProcessContainer) {
        initComponents();
        this.p = p;
        this.userProcessContainer = userProcessContainer;
        populateData();
         this.setSize(1680, 1050);
    }

    public void populateData() {
        try {
            hospitalName.setText(p.getHospital().getName());
            hospContactNo.setText(p.getHospital().getPhonenumber());
            hospAddress.setText(p.getHospital().getStreetaddress() + ", " + p.getHospital().getCity() + ", " + p.getHospital().getZipcode());
            vehicleNumber.setText(p.getAmbulancedriver().getAmbulanceNumber());
            driverName.setText(p.getAmbulancedriver().getDriverFirstName() + " " + p.getAmbulancedriver().getDriverLastName());
            driverContactNumber.setText(p.getAmbulancedriver().getPhoneNumber());
            patientCareStaffContactNo.setText(p.getPatientcarestaff().getPhonenumber());
            patientCareStaffName.setText(p.getPatientcarestaff().getPhonenumber());
            patientStatus.setText(p.getPatientstatus());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please wait. Your request is in progress!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hospitalName = new javax.swing.JLabel();
        hospAddress = new javax.swing.JLabel();
        hospContactNo = new javax.swing.JLabel();
        driverName = new javax.swing.JLabel();
        vehicleNumber = new javax.swing.JLabel();
        patientCareStaffName = new javax.swing.JLabel();
        driverContactNumber = new javax.swing.JLabel();
        patientStatus = new javax.swing.JLabel();
        patientCareStaffContactNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("REPORT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 32, 89, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Camp Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Camp Contact Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Private Driver Vehicle Number:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Private Driver Name:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Patient Care Staff Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Private Driver Contact Number:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Patient Care Contact Number:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Request Status:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Camp Address:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, 20));

        hospitalName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(hospitalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 282, 20));

        hospAddress.setBackground(new java.awt.Color(51, 51, 51));
        hospAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(hospAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 282, 20));

        hospContactNo.setBackground(new java.awt.Color(51, 51, 51));
        hospContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(hospContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 282, 20));

        driverName.setBackground(new java.awt.Color(51, 51, 51));
        driverName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(driverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 282, 20));

        vehicleNumber.setBackground(new java.awt.Color(51, 51, 51));
        vehicleNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(vehicleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 282, 20));

        patientCareStaffName.setBackground(new java.awt.Color(51, 51, 51));
        patientCareStaffName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(patientCareStaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 282, 20));

        driverContactNumber.setBackground(new java.awt.Color(51, 51, 51));
        driverContactNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(driverContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 282, 20));

        patientStatus.setBackground(new java.awt.Color(51, 51, 51));
        patientStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(patientStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 282, 20));

        patientCareStaffContactNo.setBackground(new java.awt.Color(51, 51, 51));
        patientCareStaffContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(patientCareStaffContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 282, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/business-report.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 260, 320));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return-button.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 40, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaJPanel workareajpanel = (PatientWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel driverContactNumber;
    private javax.swing.JLabel driverName;
    private javax.swing.JLabel hospAddress;
    private javax.swing.JLabel hospContactNo;
    private javax.swing.JLabel hospitalName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel patientCareStaffContactNo;
    private javax.swing.JLabel patientCareStaffName;
    private javax.swing.JLabel patientStatus;
    private javax.swing.JLabel vehicleNumber;
    // End of variables declaration//GEN-END:variables
}
